# Generated by Django 3.1.4 on 2020-12-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of your template', max_length=200)),
                ('file', models.FileField(help_text='The name of your template', upload_to='gateway-templates/')),
            ],
        ),
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of your gateway config', max_length=200)),
                ('ipbx_ip', models.GenericIPAddressField(help_text='The IP address of the IPBX on witch your gateway will register')),
                ('ipbx_auth_username', models.CharField(help_text='The SIP username used to register on the IPBX', max_length=200)),
                ('ipbx_auth_password', models.CharField(help_text='The SIP password used to register on the IPBX', max_length=200)),
                ('gateway_ip', models.GenericIPAddressField(help_text='The IP adress of your gateway')),
                ('gateway_mask', models.GenericIPAddressField(default='255.255.255.0', help_text='The netmask of your gateway')),
                ('gateway_gw', models.GenericIPAddressField(blank=True, default='', help_text='The defaut gateway of your gateway', null=True)),
                ('gateway_password', models.CharField(blank=True, help_text='The admin password of the gateway', max_length=200)),
                ('tone', models.CharField(choices=[('FR', 'French')], max_length=2)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gwconf.template')),
            ],
        ),
    ]
