# Generated by Django 3.1.4 on 2020-12-22 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of your gateway config', max_length=200)),
                ('ipbx_ip', models.GenericIPAddressField(help_text='The IP address of the IPBX on witch your endpoint will register')),
                ('gateway_ip', models.GenericIPAddressField(help_text='The IP adress of your gateway')),
                ('gateway_mask', models.GenericIPAddressField(default='255.255.255.0', help_text='The netmask of your gateway')),
                ('gateway_gw', models.GenericIPAddressField(blank=True, default='', help_text='The defaut gateway of your gateway', null=True)),
                ('gateway_password', models.CharField(blank=True, help_text='The admin password of the gateway', max_length=200)),
                ('gateway_ntp', models.GenericIPAddressField(blank=True, default='', help_text='The ntp server used by the gateway', null=True)),
                ('gateway_dns1', models.GenericIPAddressField(blank=True, default='', help_text='The dns serveur used by the gateway', null=True)),
                ('tone', models.CharField(choices=[('FR', 'FR')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of your template', max_length=200)),
                ('file', models.FileField(help_text='The name of your template', upload_to='endpoint-templates/')),
                ('max_line_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LineConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Some information about the line', max_length=200)),
                ('ipbx_auth_username', models.CharField(help_text='The SIP username used to register on the IPBX', max_length=200)),
                ('ipbx_auth_password', models.CharField(help_text='The SIP password used to register on the IPBX', max_length=200)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpointconf.endpointconfig')),
            ],
        ),
        migrations.AddField(
            model_name='endpointconfig',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='endpointconf.template'),
        ),
    ]
